services:
  sensor:
    build:
      context: ./sensor
    container_name: sensor
    restart: unless-stopped

  receiver:
    build:
      context: ./receiver
    container_name: receiver
    restart: unless-stopped


  
