services:
  sensor1:
    build:
      context: ./sensor
    container_name: sensor1
    restart: unless-stopped
    environment:
      SENSOR_ID: 1
      SENSOR_TYPE: electricity
      SENSOR_START_POINT: 345.09
      SENSOR_TIMEOUT: 1
    depends_on:
      - gateway



  gateway:
    build:
      context: ./gateway
    container_name: gateway
    restart: unless-stopped
    env_file:
      - gateway/.env
    depends_on:
      - server
    networks:
      - cloud
  
  server:
    build:
      context: ./server
    container_name: server
    restart: unless-stopped
    env_file:
      - server/.env
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - cloud
      - storage_pg_network
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"
    depends_on:
      - server
    networks:
      - cloud

networks:
  cloud:
    driver: bridge
  storage_pg_network:
    external: true